version: '3.8'
services:
  database:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: japroject_pass
      POSTGRES_USER: japroject
      POSTGRES_DB: japroject
